

trigger: none
pool: selfhostagent

parameters:
- name: environments
  type: string
  default: dev
  values:
  - dev
  - qa
  - prod


- name: runApply
  displayName: Run Terraform Apply?
  type: boolean
  default: false



variables:
  azureServiceConnection: "ashu-Service-connection"
  terraformfilepath: "$(System.DefaultWorkingDirectory)/env/${{ parameters.environments }}"
  backendKey: ${{ parameters.environments }}.tfstate



stages:
- stage: CodeScanning
  displayName: Scanning tflint tfsec checkov
  jobs:
  - job: LintAndCheckovJob
    displayName: Terraform Lint And Checkov
    continueOnError: true
    steps: 
    - task: PowerShell@2
      displayName: tflint
      continueOnError: true
      inputs:
        targetType: 'inline'
        script: |
          cd $(terraformfilepath)
          tflint --init
          tflint

    - task: PowerShell@2
      displayName: checkov
      continueOnError: true
      inputs:
        targetType: 'inline'
        script: |
          $env:HOME = "$env:USERPROFILE"
          cd $(terraformfilepath)
          checkov -d . --framework terraform

    - task: AzureCLI@2
      displayName: TFSEC
      continueOnError: true
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          cd $(terraformfilepath)
          tfsec



- stage: TfPlanInfraCost
  dependsOn: CodeScanning
  displayName: Terraform Validate plan and infra cost

  jobs:
  - job: terraformPlanInfraCost
    continueOnError: true
    displayName: Terraform plan Infra Cost
    steps: 
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(terraformfilepath)'
        backendServiceArm: $(azureServiceConnection)
        backendAzureRmResourceGroupName: 'rg-bknd-ashu'
        backendAzureRmStorageAccountName: 'stgbkendpipelineashu'
        backendAzureRmContainerName: 'tfcontainer'
        backendAzureRmKey: $(backendKey)

    - task: TerraformTask@5
      displayName: terraform validate
      continueOnError: true
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(terraformfilepath)'


    - task: TerraformTask@5
      continueOnError: true
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(terraformfilepath)'
        commandOptions: '-out=tfplan'
        environmentServiceNameAzureRM: '$(azureServiceConnection)'


    - task: PublishPipelineArtifact@1
      displayName: publish Plan output
      inputs:
        targetPath: '$(terraformfilepath)/tfplan'
        artifact: 'PlankiFile'
        publishLocation: 'pipeline'

    - task: CopyFiles@2
      displayName: copy publish tfplan to new folder
      inputs:
        SourceFolder: '$(terraformfilepath)'
        Contents: 'tfplan'
        TargetFolder: '$(Pipeline.Workspace)'
        OverWrite: true

  # - job: InfraCost
  #   continueOnError: true
  #   displayName: Terraform InfraCost
  #   dependsOn: terraformPlan
  #   steps: 
  #   - task: DownloadPipelineArtifact@2
  #     displayName: Download Artifact
  #     inputs:
  #       buildType: 'current'
  #       artifactName: 'PlankiFile'
  #       itemPattern: 'tfplan'
  #       targetPath: '$(terraformfilepath)/'


    - task: InfracostSetup@2
      displayName: DownloadInfraSetup
      inputs:
        apiKey: 'ico-qbgidTFYPSyYajjiobnp8QywUx08BGMO'
        version: '0.10.x'
        currency: 'INR'


    - task: CmdLine@2
      displayName: InfraCost Breakdown
      inputs:
        script: |
          cd $(terraformfilepath)
          infracost breakdown --path . --format table



- stage: ManualValidation
  displayName: Manual Validation Check
  dependsOn: TfPlanInfraCost
  jobs:
  - job: ManualValidationJob
    pool: server
    steps:
    - task: ManualValidation@1
      displayName: ManualValidation
      inputs:
        approvers: 'ashuchauhanks@gmail.com'
        instructions: 'pls check and approve, if valid'


- stage: Apply
  displayName: Terraform Apply
  condition: eq('${{ parameters.runApply }}', true)

  dependsOn: ManualValidation
  jobs:
  - job: Apply
    displayName: Terraform apply
    steps:
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(terraformfilepath)'
        backendServiceArm: $(azureServiceConnection)
        backendAzureRmResourceGroupName: 'rg-bknd-ashu'
        backendAzureRmStorageAccountName: 'stgbkendpipelineashu'
        backendAzureRmContainerName: 'tfcontainer'
        backendAzureRmKey: $(backendKey)

    - task: DownloadPipelineArtifact@2
      displayName: Download Artifact
      inputs:
        buildType: 'current'
        artifactName: 'PlankiFile'
        itemPattern: 'tfplan'
        targetPath: '$(terraformfilepath)/'


    - task: TerraformTask@5
      displayName: Terraform apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(terraformfilepath)'
        commandOptions: 'tfplan'
        environmentServiceNameAzureRM: '$(azureServiceConnection)'
